<!-- Bootstrap -->
<link href="<?=$root;?>css/bootstrap.min.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Roboto:400italic,300,700,300italic,400' rel='stylesheet' type='text/css'>

<link href="<?=$root;?>css/style.css" rel="stylesheet">
<link href="<?=$root;?>css/custom_style.css" rel="stylesheet">
<!--    <link href="css/colors.css" rel="stylesheet">-->


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="<?=$root;?>js/bootstrap.min.js"></script>
<script src="<?=$root;?>js/modernizr.js"></script>
<script src="<?=$root;?>js/modernizrTouch.js"></script>
<script src="<?=$root;?>js/holder.min.js"></script>




<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->