
<section class="ipiresies">

  <div class="row">
    <div class=" text-center   ">
      <h2 class="large wow fadeInUp ">Web Design Agency</h2>
      <!--<p class="wow fadeInUp "data-wow-delay="1s"> in Greece </p>-->

    </div>
  </div>
  <div class="row margin-top-50">
    <div class="col-md-4">
      <div class="icon text-center wow fadeInUp" data-wow-delay="0.3s">
        <div class="border-icon cycle lightgray-bg-icon"><i class="fa fa-code fa-3x "></i></div>
        <div class="icon-body">
          <h2>Clean & Organized Code</h2>
          <p>Vae, calcaria! Cum devatio favere, omnes fideses visum gratis, fidelis vigiles. Cum calceus credere, omnes historiaes vitare clemens, azureus rumores. Burguss sunt vitas de clemens barcas. Barbatus, nobilis vitas etiam carpseris de azureus,
            noster cobaltum.
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="icon text-center wow fadeInUp" data-wow-delay="0.6s">
        <div class="border-icon lightgray-bg-icon"><i class="fa fa-desktop  fa-3x "></i></div>

        <div class="icon-body">
          <h2>Responsive Layout</h2>
          <p>Vae, calcaria! Cum devatio favere, omnes fideses visum gratis, fidelis vigiles. Cum calceus credere, omnes historiaes vitare clemens, azureus rumores. Burguss sunt vitas de clemens barcas. Barbatus, nobilis vitas etiam carpseris de azureus,
            noster cobaltum.
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="icon text-center wow fadeInUp" data-wow-delay="0.9s">
        <i class="fa fa-css3 fa-3x color_orangered"></i>
        <div class="icon-body">
          <h2>Powered by Bootstrap</h2>
          <p>Vae, calcaria! Cum devatio favere, omnes fideses visum gratis, fidelis vigiles. Cum calceus credere, omnes historiaes vitare clemens, azureus rumores. Burguss sunt vitas de clemens barcas. Barbatus, nobilis vitas etiam carpseris de azureus,
            noster cobaltum.
          </p>
        </div>
      </div>
    </div>
  </div>

</section>
