<div class="row grid-sm-gutter dotted">
  <h2 class="text-right">Latest Work</h2>
  <div class="col-md-4">
    <a class="gallery" href="<?=$root;?>src/image2.jpg">
      <img src="<?=$root;?>src/image2.jpg" class="img-responsive" alt="" />
      <div class="content">
        <h2>Some Title</h2>
        <p>some description some description </p>
      </div>
    </a>
  </div>
  <div class="col-md-4 ">
    <a class="gallery" href="<?=$root;?>src/imac.jpg">
      <img src="<?=$root;?>src/imac.jpg" class="img-responsive" alt="" />
    </a>
  </div>
  <div class="col-md-4 ">
    <a class="gallery" href="<?=$root;?>src/image3.jpg">
      <img src="<?=$root;?>src/image3.jpg" class="img-responsive" alt="" />
    </a>
  </div>

  <div class="col-md-4 ">
    <a class="gallery" href="<?=$root;?>src/image2.jpg">
      <img src="<?=$root;?>src/image2.jpg" class="img-responsive" alt="" />
    </a>
  </div>
  <div class="col-md-4 ">
    <a class="gallery" href="<?=$root;?>src/imac.jpg">
      <img src="<?=$root;?>src/imac.jpg" class="img-responsive" alt="" />
    </a>
  </div>
  <div class="col-md-4 ">
    <a class="gallery" href="<?=$root;?>src/image3.jpg">
      <img src="<?=$root;?>src/image3.jpg" class="img-responsive" alt="" />
    </a>
  </div>
</div>
