<footer class="bg-black font-xs">
    <div class="container">
        <div class="row padding-20 margin-bottom-20">

            <div class="col-md-12 margin-top-20 text-center">
                Copyright © <?= date("Y");?> adesign
            </div>




        </div>

    </div>
</footer>


<script>

    // get location url add a folder
    var locationUrl = window.location.origin+"/adesign/";
    console.log(locationUrl);
</script>

<script src="http://<?=$domain;?>/adesign/js/scripts.js"></script>

