  <footer class="bg-black font-xs">
    <div class="container">
      <div class="row padding-20 margin-bottom-40">

        <div class="col-md-12 margin-top-20">
          <div class="logo grey">
            <span class="rotator" data-speed="1500" data-effe="fadeIn">A,W,E,S,O,M,E</span> <span class="bold">Design</span>
          </div>
        </div>



        <div class="col-md-3">
          <h4 class="sepeartor-1 margin-bottom-20"> About </h4>
          <ul class="list-unstyled">
            <li><a href="">um dolor sit.</a></li>
            <li><a href="">totam? Architecto?</a></li>
            <li><a href="">poris itaque nulla.</a></li>
            <li><a href="">repellat ullam?</a></li>
            <li><a href="">Lorem ipsum dolor sit.</a></li>
            <li><a href="">Lorem ipsum dolor sit amet.</a></li>
            <li><a href="">Lorem ipsum dolor.</a></li>
          </ul>
        </div>
        <div class="col-md-3">
          <h4 class="small-line"> About </h4>
          <ul class="list-unstyled">
            <li><a href="#">Lorem ipsum dolor sit amet.</a> </li>
            <li><a href="#">Corporis facere sit voluptates voluptatum.</a> </li>
            <li><a href="#">Cupiditate laudantium qui sapiente voluptatum?</a> </li>
            <li><a href="#">Et magni officiis placeat quos?</a> </li>
            <li><a href="#">Debitis quos saepe sequi sint.</a> </li>
            <li><a href="#">Architecto at est explicabo optio!</a> </li>
          </ul>
        </div>
        <div class="col-md-3">
          <h4 class="color_grey"> About </h4>
          <ul class="list-unstyled">
            <li><a href="#">Lorem ipsum dolor sit amet.</a> </li>
            <li><a href="#">Cupiditate iste nam quisquam voluptatum.</a> </li>
            <li><a href="#">Atque nulla quas vero voluptatibus?</a> </li>
            <li><a href="#">Ducimus fugiat neque nisi? Soluta.</a> </li>
            <li><a href="#">Dicta fuga quae quam repudiandae.</a> </li>
          </ul>
        </div>
        <div class="col-md-3">
          <h4 class="color_grey"> About </h4>
          <ul class="list-unstyled">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi cum deleniti dolorem eaque eveniet magni
              maiores minima nam odit officiis omnis perferendis porro quaerat rem repellendus sit, tempora ullam
              voluptatem!</p>
          </ul>


          <div class="form-group">
            <div class="row">
              <div class="col-md-8">
                <input type="text" placeholder="Email" class="form-control">
              </div>
              <div class="col-md-4">
                <button class="btn btn-sm form-control">Ok</button>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </footer>
